name: pre-commit-ci
on:
  pull_request:
    branches:
      - master
jobs:
  pre-commit-ci:
    name: Run pre-commit checks on changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run pre-commit checks on any files changed between base_ref and HEAD
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --from-ref origin/${{github.base_ref}} --to-ref HEAD
