name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
on: [release]

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish any distribution ğŸ“¦ to Test PyPI
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          ignore_dev_requirements: "yes"
      - name: Publish tagged distribution ğŸ“¦ to PyPI
        uses: JRubics/poetry-publish@v1.17
        if: startsWith(github.ref, 'refs/tags')
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
